namespace MSVS
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:2.0.50727.3053
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------

	using System.Xml.Serialization;
	using System.ComponentModel;
	using System.ComponentModel.Design;
	using System.Drawing.Design;
//	using efx.Design;
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.ComponentModel.DescriptionAttribute("The switch associated to the property is rendered in the command line only when the Boolean user property value is set to On.")]
	[EditorAttribute(typeof(BasicTypeEditor),typeof(UITypeEditor))]
	public partial class BooleanProperty : Property {
	    
	    private string switchField;
	    private bool defaultValueField;
	    public BooleanProperty() { this.defaultValueField = false; }
	    [XmlAttribute] public string Switch { get { return this.switchField; } set { this.switchField = value; } }
	    [XmlAttribute,System.ComponentModel.DefaultValueAttribute(false)] public bool DefaultValue { get { return this.defaultValueField; } set { this.defaultValueField = value; } }
	}
}
