namespace MSVS
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:2.0.50727.3053
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------

	using System.ComponentModel;
	using System.Drawing.Design;
	using System.Xml.Serialization;

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class EnumValue {
	    private string switchField;
	    private string valueField;
	    private string displayNameField;

	    /// <remarks/>
	    [XmlAttribute()]
	    public string Switch { get { return this.switchField; }
	        set { this.switchField = value; }
	    }

	    /// <remarks/>
	    [XmlAttribute(DataType="integer")]
	    public string Value {
	        get {
	            return this.valueField;
	        }
	        set {
	            this.valueField = value;
	        }
	    }
	    
	    /// <remarks/>
	    [XmlAttribute()]
	    public string DisplayName {
	        get {
	            return this.displayNameField;
	        }
	        set {
	            this.displayNameField = value;
	        }
	    }
		public override string ToString()
		{
			return this.displayNameField;
		}
	}
}
