namespace MSVS
{
	using System;
	using System.ComponentModel;
	using System.ComponentModel.Design;
	using System.Drawing.Design;
	using System.Xml.Serialization;
	
//	using efx.Design;

	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:2.0.50727.3053
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------
	
	/// <remarks/>
	[Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.ComponentModel.DescriptionAttribute("The value of the user property is chosen from a predefined set of constant values. Each value in the set has an associated switch that is rendered into the command line, depending on the user choice. One of these values in the set is considered to be the default value. This type of property is useful when configuring switches that are excluding one another on the command line.")]
	public partial class EnumProperty : Property {
	    
	    private EnumPropertyValues valuesField;
	    private string defaultValueField;

	    public EnumProperty() { this.defaultValueField = "0"; valuesField = new EnumPropertyValues(); } 
	    /// <remarks/>
	    [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.ComponentModel.TypeConverterAttribute(typeof(BrowsableTypeConverter))]
		[System.ComponentModel.DescriptionAttribute(@"")]
	    public EnumPropertyValues Values { get { return this.valuesField; } set { this.valuesField = value; } }
	    
	    /// <remarks/>
	    [XmlAttribute(DataType="integer")]
		[System.ComponentModel.DescriptionAttribute(@"")]
	    public string DefaultValue {get {return this.defaultValueField; } set { this.defaultValueField = value; } }

	
	}
}
