namespace MSVS
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:2.0.50727.3053
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------

	using System.Xml.Serialization;
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.ComponentModel.DescriptionAttribute("The value is a number")]
	public partial class IntegerProperty : Property {
	    
	    private string switchField;
	    private string defaultValueField;
	    
	    public IntegerProperty() {
	        this.defaultValueField = "0";
	    }

	    /// <remarks/>
	    [XmlAttribute()]
		[System.ComponentModel.DescriptionAttribute(@"Both integer and string user properties have a specific way of rendering the switch in the command line. The switch can contain the keyword [value] in its definition. When the user property has a value specified by the user (either integer or string), the switch is rendered by replacing the keyword [value] with the actual value. For example, an integer property called Warning Level can have the switch set to /W[value] and, depending on whether the user sets the property value to 0, 1, or 2, the rendered switch will be /W0, /W1, or /W2")]
	    public string Switch {
	        get {
	            return this.switchField;
	        }
	        set {
	            this.switchField = value;
	        }
	    }
	    
	    /// <remarks/>
	    [XmlAttribute(DataType="integer")]
	    [System.ComponentModel.DefaultValueAttribute("0")]
	    public string DefaultValue {
	        get {
	            return this.defaultValueField;
	        }
	        set {
	            this.defaultValueField = value;
	        }
	    }
	}
}
