namespace MSVS
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:2.0.50727.3053
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------

	using System.Xml.Serialization;
	using System.ComponentModel;
	using System.ComponentModel.Design;
	using System.Drawing.Design;
	/// <remarks/>
	[XmlIncludeAttribute(typeof(IntegerProperty))]
	[XmlIncludeAttribute(typeof(BooleanProperty))]
	[XmlIncludeAttribute(typeof(EnumProperty))]
	[XmlIncludeAttribute(typeof(StringProperty))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class Property {
	    
	    private string nameField;
	    private bool isReadOnlyField;
	    private string displayNameField;
	    private string descriptionField;
	    private string propertyPageNameField;
	    private string categoryField;
	    private string helpContextField;
	    private string helpFileField;
	    private string helpURLField;
	    
	    public Property() {
	        this.isReadOnlyField = false;
	        this.propertyPageNameField = "General";
	    }
	    
	    /// <remarks/>
	    [XmlAttribute()]
	    public string Name {
	        get {
	            return this.nameField;
	        }
	        set {
	            this.nameField = value;
	        }
	    }
	    
	    /// <remarks/>
	    [XmlAttribute()]
	    [System.ComponentModel.DefaultValueAttribute(false)]
	    public bool IsReadOnly {
	        get {
	            return this.isReadOnlyField;
	        }
	        set {
	            this.isReadOnlyField = value;
	        }
	    }
	    
	    /// <remarks/>
	    [XmlAttribute()]
	    public string DisplayName {
	        get {
	            return this.displayNameField;
	        }
	        set {
	            this.displayNameField = value;
	        }
	    }
	    
	    /// <remarks/>
	    [XmlAttribute()]
	    public string Description {
	        get {
	            return this.descriptionField;
	        }
	        set {
	            this.descriptionField = value;
	        }
	    }
	    
	    /// <remarks/>
	    [XmlAttribute()]
	    [System.ComponentModel.DefaultValueAttribute("General")]
	    public string PropertyPageName {
	        get {
	            return this.propertyPageNameField;
	        }
	        set {
	            this.propertyPageNameField = value;
	        }
	    }
	    
	    /// <remarks/>
	    [XmlAttribute()]
	    public string Category {
	        get {
	            return this.categoryField;
	        }
	        set {
	            this.categoryField = value;
	        }
	    }
	    
	    /// <remarks/>
	    [XmlAttribute(DataType="integer")]
	    public string HelpContext {
	        get {
	            return this.helpContextField;
	        }
	        set {
	            this.helpContextField = value;
	        }
	    }
	    
	    /// <remarks/>
	    [XmlAttribute()]
	    public string HelpFile {
	        get {
	            return this.helpFileField;
	        }
	        set {
	            this.helpFileField = value;
	        }
	    }
	    
	    /// <remarks/>
	    [XmlAttribute()]
	    public string HelpURL {
	        get {
	            return this.helpURLField;
	        }
	        set {
	            this.helpURLField = value;
	        }
	    }
	}
	
}
