namespace MSVS
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:2.0.50727.3053
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------

	using System.Xml.Serialization;
	using System.ComponentModel;
	using System.ComponentModel.Design;
	using System.Drawing.Design;
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.ComponentModel.DescriptionAttribute(@"Both integer and string user properties have a specific way of rendering the switch in the command line. The switch can contain the keyword [value] in its definition. When the user property has a value specified by the user (either integer or string), the switch is rendered by replacing the keyword [value] with the actual value. For example, an integer property called Warning Level can have the switch set to /W[value] and, depending on whether the user sets the property value to 0, 1, or 2, the rendered switch will be /W0, /W1, or /W2")]
	public partial class StringProperty : Property {
	    
	    private string switchField;
	    private string defaultValueField;
	    private bool delimitedField;
	    private string delimitersField;
	    private bool inheritableField;
	    
	    public StringProperty() {
	        this.delimitedField = false;
	        this.delimitersField = ";,";
	        this.inheritableField = false;
	    }
	    
	    /// <remarks/>
	    [XmlAttribute()]
		[System.ComponentModel.DescriptionAttribute("This is the switch that will be added to the command line when the property is set by the user.")]
	    public string Switch {
	        get {
	            return this.switchField;
	        }
	        set {
	            this.switchField = value;
	        }
	    }
	    
	    /// <remarks/>
	    [XmlAttribute()]
		[System.ComponentModel.DescriptionAttribute("")]
	    public string DefaultValue {
	        get {
	            return this.defaultValueField;
	        }
	        set {
	            this.defaultValueField = value;
	        }
	    }
	    
	    /// <remarks/>
	    [XmlAttribute()]
		[System.ComponentModel.DescriptionAttribute("(see: 'Delimiters')")]
	    [System.ComponentModel.DefaultValueAttribute(false)]
	    public bool Delimited {
	        get {
	            return this.delimitedField;
	        }
	        set {
	            this.delimitedField = value;
	        }
	    }
	    
	    /// <remarks/>
	    [XmlAttribute()]
	    [System.ComponentModel.DefaultValueAttribute(";,")]
		[System.ComponentModel.DescriptionAttribute("defines the characters allowed to separate the items in the list.")]
	    public string Delimiters {
	        get {
	            return this.delimitersField;
	        }
	        set {
	            this.delimitersField = value;
	        }
	    }
	    
	    /// <remarks/>
	    [XmlAttribute()]
	    [System.ComponentModel.DefaultValueAttribute(false)]
		[System.ComponentModel.DescriptionAttribute("If set to True, the value of the property will be inherited from the project level.")]
	    public bool Inheritable {
	        get {
	            return this.inheritableField;
	        }
	        set {
	            this.inheritableField = value;
	        }
	    }
	}
}
