namespace MSVS
{
	//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Xml.Serialization;
//using efx.Design;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class VisualStudioToolFile {
    
    private VisualStudioToolFileRules itemField;
    private string nameField;
    
    /// <remarks/>
    [
    	XmlElement("Rules", Form=System.Xml.Schema.XmlSchemaForm.Unqualified),
    	TypeConverterAttribute(typeof(BrowsableTypeConverter))
    ]
    public VisualStudioToolFileRules Item { get { return this.itemField; } set { this.itemField = value; } }
    
    /// <remarks/>
    [XmlAttribute(),DefaultValueAttribute("new (VisualStudioToolFileRules)")]
    public string Name { get { return this.nameField; } set { this.nameField = value; }
    }
}



















}